# Generated by Django 4.1.3 on 2023-02-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('users', '0007_alter_user_options_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_places',
            field=models.ManyToManyField(to='places.place'),
        ),
    ]
