version: 0.2

env:
  variables:
    PROJECT_NAME: kemet

phases:
  install:
    commands:
      # Install dependencies
      - pip install -r requirements.txt
  build:
    commands:
      # Compile static files
      - python manage.py collectstatic --noinput

artifacts:
  files:
    - '**/*'
