# Generated by Django 4.1.3 on 2023-01-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_alter_places_address_alter_places_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
